config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'
  get 'comments/destroy'
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end

  get 'homes/top'
  root to: 'homes#top'

  scope module: :public do

    get 'users/log_out_confirm'
    get '/search', to: 'searchs#search'
    get 'category' => 'posts#category'


    resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end

    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]
    end

    resources :users, only:[:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'favorites' => 'users#favorites'

       # 退会確認画面
      get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
       # 論理削除用のルーティング
      patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length:{maximum:100}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  	belongs_to :post
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  # 新着順へ並び方を変更する機能
  default_scope -> { order(created_at: :desc) }

  belongs_to :user

  # コメント機能
  has_many :comments, dependent: :destroy

  # いいね機能
  has_many :favorites, dependent: :destroy

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  has_many :genres, dependent: :destroy

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_one_attached :post_image
  def get_post_image(width, height)
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :title, presence: true, length:{maximum:15}
  validates :post_image, presence: true
  validates :comment, presence: true, length:{maximum:200}
  validates :brand, presence: true
  validates :price, presence: true, numericality: {only_integer: true}
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  # 性別の表示
  enum sex: { men: 0, women: 1}

  # コメント機能
  has_many :comments, dependent: :destroy

  # いいね機能
  has_many :favorites, dependent: :destroy

  # フォローをした、されたの関係
  # フォローをした側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローをされた側
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使用する
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
   followings.include?(user)
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  has_one_attached :profile_image
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: []).processed
  end

  # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'aaa@aaa.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'ゲスト'
      user.introduction = 'ゲスト'
    end
  end

  validates :name, presence: true, length:{maximum:10}
  validates :introduction, length:{maximum:200}
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "つの問題") %>により保存できませんでした。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clothes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark ">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Clothes</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-exoanded="false" aria-label="Toggle navigation" id="navbar-button">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto justify-content-center">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                    <i class="fas fa-user-tie"></i> My page
                  <% end %>
                </li>
                <li>
                  <%= link_to category_path, class: "nav-link text-light" do %>
                    <i class="fas fa-tshirt"></i>Item-Category
                  <% end %>
                </li>
                <li>
                  <%= link_to posts_path, class: "nav-link text-light" do %>
                    <i class="far fa-address-card"></i>Posts
                  <% end %>
                </li>

                <li>
                  <%= link_to users_log_out_confirm_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i>Log_out
                  <% end %>
                </li>

                <li class = "ml-3">
                  <%= render 'public/searchs/form' %>
                </li>
              <% else %>
                <li>
                   <%= link_to root_path, class: "nav-link text-light" do %>
                     <i class="fas fa-home"></i>Home
                   <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="text-center text-white pt-5 pb-4">
      <p>Portfolio.clothes</p>
    </footer>
  </body>
</html>